Update FundMe.sol
PatrickAlphaC/fund_me pull request #14
Opened 2022-01-06 05:29 UTC by aviralgoel

added better comments

2022-01-09 11:18 UTC, DarshGupta1910 reviewed
Looks Good to me.

2022-01-11 04:16 UTC, PatrickAlphaC requested changes
Just one thing and then it's good!

2022-01-11 04:16 UTC, PatrickAlphaC commented on FundMe.sol
> +    //modifier: https://medium.com/coinmonks/solidity-tutorial-all-about-modifiers-a86cf81c14cb#:~:text=The%20Solidity%20documentation%20define%20a%20modifier%20as%20follow%3A,of%20the%20function%20t
```suggestion
    //modifier: https://medium.com/coinmonks/solidity-tutorial-all-about-modifiers-a86cf81c14cb
```

2022-01-11 04:16 UTC, merged

2022-01-11 04:16 UTC, PatrickAlphaC commented
Thank you!